version: '2'
services:
  solar-panel-app:
    image: $REGISTRY_URI/ucu-class/solar-panel-emulator:$STUDENT_NAME-0.1
    environment:
      - KAFKA_BROKERS=$KAFKA_BROKERS # workaround ecs env limitation
    logging:
      driver: awslogs
      options:
        awslogs-group: streaming-ucu
        awslogs-region: us-east-1
        awslogs-stream-prefix: $STUDENT_NAME
